from datetime import date

from app.schemas.dashboard import DashboardContent

DEVELOPMENT_CREATOR_ID = "maya-chen"

DEVELOPMENT_POSTS: tuple[DashboardContent, ...] = (
    DashboardContent(
        id="maya-creative-reset",
        title="The 20-minute creative reset",
        platform="Instagram",
        content_type="Reel",
        category="Creative systems",
        views=124_000,
        likes=8_400,
        comments=526,
        shares=2_211,
        engagement_rate=9.0,
        published_at=date(2026, 8, 9),
    ),
    DashboardContent(
        id="maya-notion-system",
        title="My Notion system is not a second brain",
        platform="LinkedIn",
        content_type="Text post",
        category="Solo business",
        views=38_000,
        likes=2_350,
        comments=302,
        shares=312,
        engagement_rate=7.8,
        published_at=date(2026, 8, 7),
    ),
    DashboardContent(
        id="maya-workflow-energy",
        title="3 signs your workflow is leaking energy",
        platform="TikTok",
        content_type="Video",
        category="Creative systems",
        views=91_000,
        likes=6_910,
        comments=611,
        shares=1_637,
        engagement_rate=10.1,
        published_at=date(2026, 8, 5),
    ),
    DashboardContent(
        id="maya-studio-week",
        title="A realistic week for a one-person studio",
        platform="Instagram",
        content_type="Carousel",
        category="Creative practice",
        views=67_000,
        likes=4_050,
        comments=286,
        shares=1_840,
        engagement_rate=9.2,
        published_at=date(2026, 8, 2),
    ),
    DashboardContent(
        id="maya-optimize-day",
        title="Stop optimizing the wrong part of your day",
        platform="LinkedIn",
        content_type="Text post",
        category="Creative systems",
        views=26_200,
        likes=1_470,
        comments=214,
        shares=198,
        engagement_rate=7.2,
        published_at=date(2026, 7, 30),
    ),
    DashboardContent(
        id="maya-work-slower",
        title="The permission slip to work slower",
        platform="Instagram",
        content_type="Carousel",
        category="Creative practice",
        views=52_200,
        likes=3_850,
        comments=244,
        shares=1_406,
        engagement_rate=10.5,
        published_at=date(2026, 7, 27),
    ),
)
